# Generated by Django 5.2.7 on 2025-11-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_otpverification_signup_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
