# Generated by Django 5.2.7 on 2025-11-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_max_admins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(max_length=50),
        ),
    ]
