# Generated by Django 5.2.7 on 2026-01-23 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('previous_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('revised_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='exams.examresult')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_concerns', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_concerns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_concerns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['result', 'status'], name='exam_concer_result__6ce9c3_idx'), models.Index(fields=['student', 'created_at'], name='exam_concer_student_f178ef_idx')],
            },
        ),
    ]
