# Generated by Django 5.2.7 on 2025-12-03 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.IntegerField()),
                ('joining_date', models.DateTimeField()),
                ('qualification', models.CharField(max_length=255)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('id_proof_url', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
