# Generated by Django 5.2.7 on 2026-01-18 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_announcement_attendence', '0005_timetableentry'),
        ('members', '0003_parentprofile_parentstudentrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='class_announcement_attendence.schoolclass'),
        ),
    ]
