# Generated by Django 5.2.7 on 2026-01-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_studentprofile_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_id',
        ),
    ]
