# Generated by Django 5.2.7 on 2026-02-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_announcement_attendence', '0005_timetableentry'),
        ('core', '0007_user_is_setup_complete'),
        ('members', '0005_remove_studentprofile_class_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('tenant', 'school_class', 'roll_number')},
        ),
    ]
