# Generated by Django 5.2.7 on 2026-02-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_setup_complete'),
        ('members', '0006_alter_studentprofile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='core.tenant'),
            preserve_default=False,
        ),
    ]
