# Generated by Django 5.2.7 on 2026-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('graded', 'Graded'), ('late', 'Late Submission')], default='pending', max_length=20),
        ),
    ]
