# Generated by Django 5.2.7 on 2025-12-03 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_user_is_setup_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=255, unique=True)),
                ('admission_date', models.DateTimeField()),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('class_id', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=50)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_number', models.CharField(blank=True, max_length=20)),
                ('roll_number', models.PositiveIntegerField()),
                ('student_contact', models.CharField(blank=True, max_length=255)),
                ('id_proof_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
