# Generated by Django 5.2.7 on 2026-02-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_teacherprofile_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='id_proof_url',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='id_proof',
            field=models.FileField(default=1, upload_to='idproofs/'),
            preserve_default=False,
        ),
    ]
