# Generated by Django 5.2.7 on 2025-11-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otpverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='reated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='isinstance_name',
            new_name='instance_name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='tenent_id',
            new_name='tenant_id',
        ),
    ]
