# Generated by Django 5.2.7 on 2025-11-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_reated_at_tenant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='signup_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
